packages:
  - packages/**

catalogs:
  e2e:
    playwright: ^1.57.0
    '@playwright/test': ^1.57.0

  next:
    next: ^16.1.5

  react19:
    '@types/react': ^19.2.9
    '@types/react-dom': ^19.2.3
    react: ^19.2.4
    react-dom: ^19.2.4

enablePrePostScripts: true

onlyBuiltDependencies:
  - '@sentry/cli'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - playwright
  - esbuild
  - sharp
