packages:
  - 'packages/**'

enablePrePostScripts: true
onlyBuiltDependencies:
  - '@sentry/cli'
  - '@swc/core'
  - 'cypress'
  - 'esbuild'
  - 'sharp'

catalogs:
  react19:
    react: 19.1.0
    react-dom: 19.1.0
    '@types/react': 19.0.12
    '@types/react-dom': 19.0.4
  e2e:
    cypress: ^14.2.1
    start-server-and-test: "^2.0.10"
