packages:
  - 'packages/**'

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    '@types/react': 18.3.12
    '@types/react-dom': 18.3.1
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    '@types/react': 19.0.0
    '@types/react-dom': 19.0.0
  e2e:
    cypress: ^13.17.0
    start-server-and-test: "^2.0.9"
