packages:
  - packages/**

catalogs:
  e2e:
    playwright: ^1.58.1
    '@playwright/test': ^1.58.1

  knip:
    knip: ^6.14.2

  vitest:
    vitest: ^4.1.0
    '@vitest/browser-playwright': ^4.1.0
    '@vitest/coverage-v8': ^4.1.0

  vite:
    vite: ^8.0.0

  next:
    next: 16.2.1-canary.3

  react19:
    '@types/react': ^19.2.10
    '@types/react-dom': ^19.2.3
    react: ^19.2.4
    react-dom: ^19.2.4

  typescript:
    typescript: ^5.9.2

enablePrePostScripts: false

trustPolicy: no-downgrade

allowBuilds:
  '@swc/core': true
  '@tailwindcss/oxide': true
  playwright: true
  esbuild: true
  sharp: true
  msw: false
