packages:
  - packages/**

catalogs:
  e2e:
    playwright: ^1.57.0
    '@playwright/test': ^1.57.0

  knip:
    knip: ^5.64.1

  next:
    next: ^16.1.0

  react19:
    '@types/react': ^19.2.7
    '@types/react-dom': ^19.2.3
    react: ^19.2.2
    react-dom: ^19.2.2

  typescript:
    typescript: ^5.9.2

enablePrePostScripts: true

onlyBuiltDependencies:
  - '@sentry/cli'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - playwright
  - esbuild
  - sharp
