packages:
  - 'packages/**'

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1

  react19rc:
    react: 19.0.0-rc-02c0e824-20241028
    react-dom: 19.0.0-rc-02c0e824-20241028

  next:
    next: 15.0.3-canary.1
