packages:
  - packages/**

catalogs:
  e2e:
    cypress: ^14.5.4
    start-server-and-test: ^2.0.13
  react19:
    '@types/react': ^19.2.0
    '@types/react-dom': ^19.2.0
    react: ^19.2.0
    react-dom: ^19.2.0

enablePrePostScripts: true

onlyBuiltDependencies:
  - '@sentry/cli'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - cypress
  - esbuild
  - sharp
