packages:
  - packages/**

catalogs:
  e2e:
    playwright: ^1.58.1
    '@playwright/test': ^1.58.1

  next:
    next: ^16.1.6

  react19:
    '@types/react': ^19.2.10
    '@types/react-dom': ^19.2.3
    react: ^19.2.4
    react-dom: ^19.2.4

enablePrePostScripts: true

onlyBuiltDependencies:
  - '@sentry/cli'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - playwright
  - esbuild
  - sharp
