import { expect, test, type Page } from '@playwright/test'
import { navigateTo } from 'e2e-shared/playwright/navigate.ts'

async function waitForHydration(page: Page) {
  await page.locator('#hydration-marker').waitFor({ state: 'hidden' })
  await page.waitForTimeout(50)
}

test.describe('routing-tour', () => {
  test('server -> a', async ({ page }) => {
    await navigateTo(page, '/app/routing-tour/start/server')

    await page.locator('a').filter({ hasText: 'a (server, prefetch)' }).click()
    await waitForHydration(page)
    await expect(page).toHaveURL(/\/app\/routing-tour\/a/)
    await expect(page).toHaveURL(url => url.search === '?from=start.server')
    await expect(page.locator('#from')).toHaveText('start.server')
    await expect(page.locator('#this')).toHaveText('a')
    await expect(page.locator('#next')).toHaveText('b')
    await expect(page.locator('#counter')).toHaveText('0')

    await page.locator('a').filter({ hasText: 'Next' }).click()
    await waitForHydration(page)
    await expect(page).toHaveURL(/\/app\/routing-tour\/b/)
    await expect(page).toHaveURL(url => url.search === '?from=a&counter=1')
    await expect(page.locator('#from')).toHaveText('a')
    await expect(page.locator('#this')).toHaveText('b')
    await expect(page.locator('#next')).toHaveText('c')
    await expect(page.locator('#counter')).toHaveText('1')

    await page.locator('a').filter({ hasText: 'Next' }).click()
    await waitForHydration(page)
    await expect(page).toHaveURL(/\/app\/routing-tour\/c/)
    await expect(page).toHaveURL(url => url.search === '?from=b&counter=2')
    await expect(page.locator('#from')).toHaveText('b')
    await expect(page.locator('#this')).toHaveText('c')
    await expect(page.locator('#next')).toHaveText('d')
    await expect(page.locator('#counter')).toHaveText('2')

    await page.locator('a').filter({ hasText: 'Next' }).click()
    await waitForHydration(page)
    await expect(page).toHaveURL(/\/app\/routing-tour\/d/)
    await expect(page).toHaveURL(url => url.search === '?from=c&counter=3')
    await expect(page.locator('#from')).toHaveText('c')
    await expect(page.locator('#this')).toHaveText('d')
    await expect(page.locator('#next')).toHaveText('a')
    await expect(page.locator('#counter')).toHaveText('3')

    await page.locator('a').filter({ hasText: 'Next' }).click()
    await waitForHydration(page)
    await expect(page).toHaveURL(/\/app\/routing-tour\/a/)
    await expect(page).toHaveURL(url => url.search === '?from=d&counter=4')
    await expect(page.locator('#from')).toHaveText('d')
    await expect(page.locator('#this')).toHaveText('a')
    await expect(page.locator('#next')).toHaveText('b')
    await expect(page.locator('#counter')).toHaveText('4')
  })

  test('server -> b', async ({ page }) => {
    await navigateTo(page, '/app/routing-tour/start/server')

    await page
      .locator('a')
      .filter({ hasText: 'b (server, no prefetch)' })
      .click()
    await waitForHydration(page)
    await expect(page).toHaveURL(/\/app\/routing-tour\/b/)
    await expect(page).toHaveURL(url => url.search === '?from=start.server')
    await expect(page.locator('#from')).toHaveText('start.server')
    await expect(page.locator('#this')).toHaveText('b')
    await expect(page.locator('#next')).toHaveText('c')
    await expect(page.locator('#counter')).toHaveText('0')

    await page.locator('a').filter({ hasText: 'Next' }).click()
    await waitForHydration(page)
    await expect(page).toHaveURL(/\/app\/routing-tour\/c/)
    await expect(page).toHaveURL(url => url.search === '?from=b&counter=1')
    await expect(page.locator('#from')).toHaveText('b')
    await expect(page.locator('#this')).toHaveText('c')
    await expect(page.locator('#next')).toHaveText('d')
    await expect(page.locator('#counter')).toHaveText('1')

    await page.locator('a').filter({ hasText: 'Next' }).click()
    await waitForHydration(page)
    await expect(page).toHaveURL(/\/app\/routing-tour\/d/)
    await expect(page).toHaveURL(url => url.search === '?from=c&counter=2')
    await expect(page.locator('#from')).toHaveText('c')
    await expect(page.locator('#this')).toHaveText('d')
    await expect(page.locator('#next')).toHaveText('a')
    await expect(page.locator('#counter')).toHaveText('2')

    await page.locator('a').filter({ hasText: 'Next' }).click()
    await waitForHydration(page)
    await expect(page).toHaveURL(/\/app\/routing-tour\/a/)
    await expect(page).toHaveURL(url => url.search === '?from=d&counter=3')
    await expect(page.locator('#from')).toHaveText('d')
    await expect(page.locator('#this')).toHaveText('a')
    await expect(page.locator('#next')).toHaveText('b')
    await expect(page.locator('#counter')).toHaveText('3')

    await page.locator('a').filter({ hasText: 'Next' }).click()
    await waitForHydration(page)
    await expect(page).toHaveURL(/\/app\/routing-tour\/b/)
    await expect(page).toHaveURL(url => url.search === '?from=a&counter=4')
    await expect(page.locator('#from')).toHaveText('a')
    await expect(page.locator('#this')).toHaveText('b')
    await expect(page.locator('#next')).toHaveText('c')
    await expect(page.locator('#counter')).toHaveText('4')
  })

  test('server -> c', async ({ page }) => {
    await navigateTo(page, '/app/routing-tour/start/server')

    await page.locator('a').filter({ hasText: 'c (client, prefetch)' }).click()
    await waitForHydration(page)
    await expect(page).toHaveURL(/\/app\/routing-tour\/c/)
    await expect(page).toHaveURL(url => url.search === '?from=start.server')
    await expect(page.locator('#from')).toHaveText('start.server')
    await expect(page.locator('#this')).toHaveText('c')
    await expect(page.locator('#next')).toHaveText('d')
    await expect(page.locator('#counter')).toHaveText('0')

    await page.locator('a').filter({ hasText: 'Next' }).click()
    await waitForHydration(page)
    await expect(page).toHaveURL(/\/app\/routing-tour\/d/)
    await expect(page).toHaveURL(url => url.search === '?from=c&counter=1')
    await expect(page.locator('#from')).toHaveText('c')
    await expect(page.locator('#this')).toHaveText('d')
    await expect(page.locator('#next')).toHaveText('a')
    await expect(page.locator('#counter')).toHaveText('1')

    await page.locator('a').filter({ hasText: 'Next' }).click()
    await waitForHydration(page)
    await expect(page).toHaveURL(/\/app\/routing-tour\/a/)
    await expect(page).toHaveURL(url => url.search === '?from=d&counter=2')
    await expect(page.locator('#from')).toHaveText('d')
    await expect(page.locator('#this')).toHaveText('a')
    await expect(page.locator('#next')).toHaveText('b')
    await expect(page.locator('#counter')).toHaveText('2')

    await page.locator('a').filter({ hasText: 'Next' }).click()
    await waitForHydration(page)
    await expect(page).toHaveURL(/\/app\/routing-tour\/b/)
    await expect(page).toHaveURL(url => url.search === '?from=a&counter=3')
    await expect(page.locator('#from')).toHaveText('a')
    await expect(page.locator('#this')).toHaveText('b')
    await expect(page.locator('#next')).toHaveText('c')
    await expect(page.locator('#counter')).toHaveText('3')

    await page.locator('a').filter({ hasText: 'Next' }).click()
    await waitForHydration(page)
    await expect(page).toHaveURL(/\/app\/routing-tour\/c/)
    await expect(page).toHaveURL(url => url.search === '?from=b&counter=4')
    await expect(page.locator('#from')).toHaveText('b')
    await expect(page.locator('#this')).toHaveText('c')
    await expect(page.locator('#next')).toHaveText('d')
    await expect(page.locator('#counter')).toHaveText('4')
  })

  test('server -> d', async ({ page }) => {
    await navigateTo(page, '/app/routing-tour/start/server')

    await page
      .locator('a')
      .filter({ hasText: 'd (client, no prefetch)' })
      .click()
    await waitForHydration(page)
    await expect(page).toHaveURL(/\/app\/routing-tour\/d/)
    await expect(page).toHaveURL(url => url.search === '?from=start.server')
    await expect(page.locator('#from')).toHaveText('start.server')
    await expect(page.locator('#this')).toHaveText('d')
    await expect(page.locator('#next')).toHaveText('a')
    await expect(page.locator('#counter')).toHaveText('0')

    await page.locator('a').filter({ hasText: 'Next' }).click()
    await waitForHydration(page)
    await expect(page).toHaveURL(/\/app\/routing-tour\/a/)
    await expect(page).toHaveURL(url => url.search === '?from=d&counter=1')
    await expect(page.locator('#from')).toHaveText('d')
    await expect(page.locator('#this')).toHaveText('a')
    await expect(page.locator('#next')).toHaveText('b')
    await expect(page.locator('#counter')).toHaveText('1')

    await page.locator('a').filter({ hasText: 'Next' }).click()
    await waitForHydration(page)
    await expect(page).toHaveURL(/\/app\/routing-tour\/b/)
    await expect(page).toHaveURL(url => url.search === '?from=a&counter=2')
    await expect(page.locator('#from')).toHaveText('a')
    await expect(page.locator('#this')).toHaveText('b')
    await expect(page.locator('#next')).toHaveText('c')
    await expect(page.locator('#counter')).toHaveText('2')

    await page.locator('a').filter({ hasText: 'Next' }).click()
    await waitForHydration(page)
    await expect(page).toHaveURL(/\/app\/routing-tour\/c/)
    await expect(page).toHaveURL(url => url.search === '?from=b&counter=3')
    await expect(page.locator('#from')).toHaveText('b')
    await expect(page.locator('#this')).toHaveText('c')
    await expect(page.locator('#next')).toHaveText('d')
    await expect(page.locator('#counter')).toHaveText('3')

    await page.locator('a').filter({ hasText: 'Next' }).click()
    await waitForHydration(page)
    await expect(page).toHaveURL(/\/app\/routing-tour\/d/)
    await expect(page).toHaveURL(url => url.search === '?from=c&counter=4')
    await expect(page.locator('#from')).toHaveText('c')
    await expect(page.locator('#this')).toHaveText('d')
    await expect(page.locator('#next')).toHaveText('a')
    await expect(page.locator('#counter')).toHaveText('4')
  })

  test('client -> a', async ({ page }) => {
    await navigateTo(page, '/app/routing-tour/start/client')

    await page.locator('a').filter({ hasText: 'a (server, prefetch)' }).click()
    await waitForHydration(page)
    await expect(page).toHaveURL(/\/app\/routing-tour\/a/)
    await expect(page).toHaveURL(url => url.search === '?from=start.client')
    await expect(page.locator('#from')).toHaveText('start.client')
    await expect(page.locator('#this')).toHaveText('a')
    await expect(page.locator('#next')).toHaveText('b')
    await expect(page.locator('#counter')).toHaveText('0')

    await page.locator('a').filter({ hasText: 'Next' }).click()
    await waitForHydration(page)
    await expect(page).toHaveURL(/\/app\/routing-tour\/b/)
    await expect(page).toHaveURL(url => url.search === '?from=a&counter=1')
    await expect(page.locator('#from')).toHaveText('a')
    await expect(page.locator('#this')).toHaveText('b')
    await expect(page.locator('#next')).toHaveText('c')
    await expect(page.locator('#counter')).toHaveText('1')

    await page.locator('a').filter({ hasText: 'Next' }).click()
    await waitForHydration(page)
    await expect(page).toHaveURL(/\/app\/routing-tour\/c/)
    await expect(page).toHaveURL(url => url.search === '?from=b&counter=2')
    await expect(page.locator('#from')).toHaveText('b')
    await expect(page.locator('#this')).toHaveText('c')
    await expect(page.locator('#next')).toHaveText('d')
    await expect(page.locator('#counter')).toHaveText('2')

    await page.locator('a').filter({ hasText: 'Next' }).click()
    await waitForHydration(page)
    await expect(page).toHaveURL(/\/app\/routing-tour\/d/)
    await expect(page).toHaveURL(url => url.search === '?from=c&counter=3')
    await expect(page.locator('#from')).toHaveText('c')
    await expect(page.locator('#this')).toHaveText('d')
    await expect(page.locator('#next')).toHaveText('a')
    await expect(page.locator('#counter')).toHaveText('3')

    await page.locator('a').filter({ hasText: 'Next' }).click()
    await waitForHydration(page)
    await expect(page).toHaveURL(/\/app\/routing-tour\/a/)
    await expect(page).toHaveURL(url => url.search === '?from=d&counter=4')
    await expect(page.locator('#from')).toHaveText('d')
    await expect(page.locator('#this')).toHaveText('a')
    await expect(page.locator('#next')).toHaveText('b')
    await expect(page.locator('#counter')).toHaveText('4')
  })

  test('client -> b', async ({ page }) => {
    await navigateTo(page, '/app/routing-tour/start/client')

    await page
      .locator('a')
      .filter({ hasText: 'b (server, no prefetch)' })
      .click()
    await waitForHydration(page)
    await expect(page).toHaveURL(/\/app\/routing-tour\/b/)
    await expect(page).toHaveURL(url => url.search === '?from=start.client')
    await expect(page.locator('#from')).toHaveText('start.client')
    await expect(page.locator('#this')).toHaveText('b')
    await expect(page.locator('#next')).toHaveText('c')
    await expect(page.locator('#counter')).toHaveText('0')

    await page.locator('a').filter({ hasText: 'Next' }).click()
    await waitForHydration(page)
    await expect(page).toHaveURL(/\/app\/routing-tour\/c/)
    await expect(page).toHaveURL(url => url.search === '?from=b&counter=1')
    await expect(page.locator('#from')).toHaveText('b')
    await expect(page.locator('#this')).toHaveText('c')
    await expect(page.locator('#next')).toHaveText('d')
    await expect(page.locator('#counter')).toHaveText('1')

    await page.locator('a').filter({ hasText: 'Next' }).click()
    await waitForHydration(page)
    await expect(page).toHaveURL(/\/app\/routing-tour\/d/)
    await expect(page).toHaveURL(url => url.search === '?from=c&counter=2')
    await expect(page.locator('#from')).toHaveText('c')
    await expect(page.locator('#this')).toHaveText('d')
    await expect(page.locator('#next')).toHaveText('a')
    await expect(page.locator('#counter')).toHaveText('2')

    await page.locator('a').filter({ hasText: 'Next' }).click()
    await waitForHydration(page)
    await expect(page).toHaveURL(/\/app\/routing-tour\/a/)
    await expect(page).toHaveURL(url => url.search === '?from=d&counter=3')
    await expect(page.locator('#from')).toHaveText('d')
    await expect(page.locator('#this')).toHaveText('a')
    await expect(page.locator('#next')).toHaveText('b')
    await expect(page.locator('#counter')).toHaveText('3')

    await page.locator('a').filter({ hasText: 'Next' }).click()
    await waitForHydration(page)
    await expect(page).toHaveURL(/\/app\/routing-tour\/b/)
    await expect(page).toHaveURL(url => url.search === '?from=a&counter=4')
    await expect(page.locator('#from')).toHaveText('a')
    await expect(page.locator('#this')).toHaveText('b')
    await expect(page.locator('#next')).toHaveText('c')
    await expect(page.locator('#counter')).toHaveText('4')
  })

  test('client -> c', async ({ page }) => {
    await navigateTo(page, '/app/routing-tour/start/client')

    await page.locator('a').filter({ hasText: 'c (client, prefetch)' }).click()
    await waitForHydration(page)
    await expect(page).toHaveURL(/\/app\/routing-tour\/c/)
    await expect(page).toHaveURL(url => url.search === '?from=start.client')
    await expect(page.locator('#from')).toHaveText('start.client')
    await expect(page.locator('#this')).toHaveText('c')
    await expect(page.locator('#next')).toHaveText('d')
    await expect(page.locator('#counter')).toHaveText('0')

    await page.locator('a').filter({ hasText: 'Next' }).click()
    await waitForHydration(page)
    await expect(page).toHaveURL(/\/app\/routing-tour\/d/)
    await expect(page).toHaveURL(url => url.search === '?from=c&counter=1')
    await expect(page.locator('#from')).toHaveText('c')
    await expect(page.locator('#this')).toHaveText('d')
    await expect(page.locator('#next')).toHaveText('a')
    await expect(page.locator('#counter')).toHaveText('1')

    await page.locator('a').filter({ hasText: 'Next' }).click()
    await waitForHydration(page)
    await expect(page).toHaveURL(/\/app\/routing-tour\/a/)
    await expect(page).toHaveURL(url => url.search === '?from=d&counter=2')
    await expect(page.locator('#from')).toHaveText('d')
    await expect(page.locator('#this')).toHaveText('a')
    await expect(page.locator('#next')).toHaveText('b')
    await expect(page.locator('#counter')).toHaveText('2')

    await page.locator('a').filter({ hasText: 'Next' }).click()
    await waitForHydration(page)
    await expect(page).toHaveURL(/\/app\/routing-tour\/b/)
    await expect(page).toHaveURL(url => url.search === '?from=a&counter=3')
    await expect(page.locator('#from')).toHaveText('a')
    await expect(page.locator('#this')).toHaveText('b')
    await expect(page.locator('#next')).toHaveText('c')
    await expect(page.locator('#counter')).toHaveText('3')

    await page.locator('a').filter({ hasText: 'Next' }).click()
    await waitForHydration(page)
    await expect(page).toHaveURL(/\/app\/routing-tour\/c/)
    await expect(page).toHaveURL(url => url.search === '?from=b&counter=4')
    await expect(page.locator('#from')).toHaveText('b')
    await expect(page.locator('#this')).toHaveText('c')
    await expect(page.locator('#next')).toHaveText('d')
    await expect(page.locator('#counter')).toHaveText('4')
  })

  test('client -> d', async ({ page }) => {
    await navigateTo(page, '/app/routing-tour/start/client')

    await page
      .locator('a')
      .filter({ hasText: 'd (client, no prefetch)' })
      .click()
    await waitForHydration(page)
    await expect(page).toHaveURL(/\/app\/routing-tour\/d/)
    await expect(page).toHaveURL(url => url.search === '?from=start.client')
    await expect(page.locator('#from')).toHaveText('start.client')
    await expect(page.locator('#this')).toHaveText('d')
    await expect(page.locator('#next')).toHaveText('a')
    await expect(page.locator('#counter')).toHaveText('0')

    await page.locator('a').filter({ hasText: 'Next' }).click()
    await waitForHydration(page)
    await expect(page).toHaveURL(/\/app\/routing-tour\/a/)
    await expect(page).toHaveURL(url => url.search === '?from=d&counter=1')
    await expect(page.locator('#from')).toHaveText('d')
    await expect(page.locator('#this')).toHaveText('a')
    await expect(page.locator('#next')).toHaveText('b')
    await expect(page.locator('#counter')).toHaveText('1')

    await page.locator('a').filter({ hasText: 'Next' }).click()
    await waitForHydration(page)
    await expect(page).toHaveURL(/\/app\/routing-tour\/b/)
    await expect(page).toHaveURL(url => url.search === '?from=a&counter=2')
    await expect(page.locator('#from')).toHaveText('a')
    await expect(page.locator('#this')).toHaveText('b')
    await expect(page.locator('#next')).toHaveText('c')
    await expect(page.locator('#counter')).toHaveText('2')

    await page.locator('a').filter({ hasText: 'Next' }).click()
    await waitForHydration(page)
    await expect(page).toHaveURL(/\/app\/routing-tour\/c/)
    await expect(page).toHaveURL(url => url.search === '?from=b&counter=3')
    await expect(page.locator('#from')).toHaveText('b')
    await expect(page.locator('#this')).toHaveText('c')
    await expect(page.locator('#next')).toHaveText('d')
    await expect(page.locator('#counter')).toHaveText('3')

    await page.locator('a').filter({ hasText: 'Next' }).click()
    await waitForHydration(page)
    await expect(page).toHaveURL(/\/app\/routing-tour\/d/)
    await expect(page).toHaveURL(url => url.search === '?from=c&counter=4')
    await expect(page.locator('#from')).toHaveText('c')
    await expect(page.locator('#this')).toHaveText('d')
    await expect(page.locator('#next')).toHaveText('a')
    await expect(page.locator('#counter')).toHaveText('4')
  })
})
