import { describe, expect, it, vi } from 'vitest'
import { createBridgeStore, publish } from './impl.isolated'

describe('impl.isolated: publish', () => {
  it('emits every present key on first publish', () => {
    const store = createBridgeStore()
    const spyA = vi.fn()
    const spyB = vi.fn()
    store.emitter.on('a', spyA)
    store.emitter.on('b', spyB)
    publish(store, new URLSearchParams('?a=1&b=2'))
    expect(store.committed?.toString()).toBe('a=1&b=2')
    expect(spyA).toHaveBeenCalledOnce()
    expect(spyB).toHaveBeenCalledOnce()
  })
  it('emits watched keys absent from the first published params', () => {
    // A hook may have read a key from the live location fallback before the
    // Bridge's first commit; if the key was removed in that window, its
    // subscribers still need to be re-checked.
    const store = createBridgeStore()
    const spy = vi.fn()
    store.watched.set('removed', 1)
    store.emitter.on('removed', spy)
    publish(store, new URLSearchParams('?a=1'))
    expect(spy).toHaveBeenCalledOnce()
  })
  it('bails out on referentially equal params', () => {
    const store = createBridgeStore()
    const params = new URLSearchParams('?a=1')
    publish(store, params)
    const spy = vi.fn()
    store.emitter.on('a', spy)
    publish(store, params)
    expect(spy).not.toHaveBeenCalled()
  })
  it('clears the render-phase holder on every publish', () => {
    const store = createBridgeStore()
    store.latest = { pathname: '/', searchParams: new URLSearchParams() }
    publish(store, new URLSearchParams('?a=1'))
    expect(store.latest).toBeNull()
  })
  it('emits only changed keys on subsequent publishes', () => {
    const store = createBridgeStore()
    publish(store, new URLSearchParams('?a=1&b=2'))
    const spyA = vi.fn()
    const spyB = vi.fn()
    store.emitter.on('a', spyA)
    store.emitter.on('b', spyB)
    publish(store, new URLSearchParams('?a=changed&b=2'))
    expect(spyA).toHaveBeenCalledOnce()
    expect(spyB).not.toHaveBeenCalled()
  })
  it('emits removed keys', () => {
    const store = createBridgeStore()
    publish(store, new URLSearchParams('?a=1&b=2'))
    const spyA = vi.fn()
    const spyB = vi.fn()
    store.emitter.on('a', spyA)
    store.emitter.on('b', spyB)
    publish(store, new URLSearchParams('?b=2'))
    expect(spyA).toHaveBeenCalledOnce()
    expect(spyB).not.toHaveBeenCalled()
  })
  it('does not emit when contents are equal', () => {
    const store = createBridgeStore()
    publish(store, new URLSearchParams('?a=1&b=2'))
    const spyA = vi.fn()
    const spyB = vi.fn()
    store.emitter.on('a', spyA)
    store.emitter.on('b', spyB)
    publish(store, new URLSearchParams('?a=1&b=2'))
    expect(spyA).not.toHaveBeenCalled()
    expect(spyB).not.toHaveBeenCalled()
    expect(store.committed?.toString()).toBe('a=1&b=2')
  })
  it('compares repeated keys by value list', () => {
    const store = createBridgeStore()
    publish(store, new URLSearchParams('?a=1&a=2&b=x'))
    const spyA = vi.fn()
    const spyB = vi.fn()
    store.emitter.on('a', spyA)
    store.emitter.on('b', spyB)
    publish(store, new URLSearchParams('?a=1&b=x'))
    expect(spyA).toHaveBeenCalledOnce()
    expect(spyB).not.toHaveBeenCalled()
  })
  it('emits a key only once per publish even when repeated', () => {
    const store = createBridgeStore()
    const spy = vi.fn()
    store.emitter.on('a', spy)
    publish(store, new URLSearchParams('?a=1&a=2'))
    expect(spy).toHaveBeenCalledOnce()
  })
})
