name: Mark as "Shipping Next"

on:
  pull_request_target:
    types: [closed]
    branches:
      - next

jobs:
  update_milestones:
    name: Update Milestones
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Check if PR was in Backlog
        id: check_milestone
        run: |
          milestone_id=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} --jq '.milestone.number')
          if [[ "$milestone_id" == "3" ]]; then
            echo "backlog_milestone=true" >> $GITHUB_OUTPUT
          else
            echo "backlog_milestone=false" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update PR milestone to "shipping next"
        if: steps.check_milestone.outputs.backlog_milestone == 'true'
        run: |
          gh api -X PATCH \
            repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }} \
            -f milestone=2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
