name: Move `master` to `next`

on:
  workflow_dispatch:

jobs:
  move-master-to-next:
    name: Move `master` to `next`
    runs-on: ubuntu-latest
    if: github.actor == 'franky47'
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
        with:
          fetch-depth: 0
      - name: Move master to next & push
        run: |
          git checkout master
          git reset --hard next
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
